Add option to create different types of QR Codes
cevi/qr-code-generator pull request #5
Opened 2023-10-14 15:05 UTC by ursforrer

#3 

The following functions were added
- Support for Vcard, Phonenumber, Link and Wifi Credentials
- Add cevi design to the whole application

2023-10-15 18:52 UTC, wp99cp requested changes
@ursforrer thank you very much for your work, the new layout/design looks amazing!

I've tested all QR-Code options, and they seem to work as expected. I've two small changes (see comments), afterwards, feel free to merge the PR. 

For now, deployment must be done manually, but I will take care of that as soon as the PR is merged.

2023-10-15 18:52 UTC, wp99cp commented on frontend/Dockerfile
> +FROM node:20 as build
I've some problems building the container with node:20.
The container gets stuck at the "npm ci" step. I had to switch the image to node:20-alpine, and then the installation worked without any issues. Is there anything against switching to alpine for that particular image? I don't see any problem with that.

2023-10-15 18:52 UTC, wp99cp commented on frontend/src/app/design-switcher/components/design-switcher/design-switcher.component.scss
> +    background-color: white;
Can we change the default color to something with a little more contrast to the background or add a small border to the radio button? Depending on the display's contrast, the clickable area isn't visible very well.

2023-10-16 16:44 UTC, ursforrer commented
@wp99cp Thanks for the code review. Changes were applied and the branch merged.

2023-10-16 16:44 UTC, merged